data_check:
  dataPath1: data/NonsurgicalMR
  dataPath2: data/SurgicalMR
  writePath: data
  # checkModels: ['A', 'ADC', 'T2_FS', 'V', 'DWI', 'P']
  checkModels: ['ADC', 'T2_FS']
  lowestResolution: [200, 200]
  lowestSize: 500

trainer:
  num_epochs: 500
  warmup: 2
  batch_size: 2
  # batch_size: 16
  resume: True
  lr: 0.001
  min_lr: 0.0000001
  optimizer: adamw
  weight_decay: 0.05
  weight_decay_end: 0.04

finetune:
  checkpoint: SppSlim

loader:
  train_ratio: 0.8
  num_workers: 0
  dataPath: /workspace/Jeming/MR/data/
  # checkModels: ['A', 'ADC', 'T2_FS', 'V', 'DWI', 'P']
  checkModels: ['ADC', 'T2_FS']
  # model_scale: [[0,4500],[0,4500]] # 对应模态的最小最大像素值，用于归一化
  model_scale: [[0,4500],[0,6000]] # 对应模态的最小最大像素值，用于归一化
  target_size: [128, 128, 64]

visualization:
  image_path: img
  for_single: False
  choose_dir: NonsurgicalMR
  choose_image: '0000095438'